Stick footer to bottom
openclimatefix/website pull request #40
Opened 2019-11-19 11:52 UTC by geekayush

Fix #5 
The footer now sticks to the bottom.
![Screenshot from 2019-11-19 17-19-54](https://user-images.githubusercontent.com/22499864/69144315-05dd3280-0af1-11ea-9545-b521a76a31a8.png)

2019-11-19 20:01 UTC, flowirtz requested changes
Awesome, thanks!
Left one small comment.

Usually I'd ask you to rewrite everything using tailwind, but I'm unhappy how we handle CSS in the repo in general, so thinking about rewriting the whole CSS setup. Doesn't matter for now.

Thanks!

2019-11-19 20:01 UTC, flowirtz commented on src/components/layout.css
> +
```suggestion

/* Ensure Footer always sticks to the bottom */
```
let's add a little comment here to explain what we are doing

2019-11-19 20:02 UTC, FWirtz commented
@all-contributors please add @geekayush for code

2019-11-20 16:33 UTC, geekayush commented
> Awesome, thanks!
> Left one small comment.
> 
> Usually I'd ask you to rewrite everything using tailwind, but I'm unhappy how we handle CSS in the repo in general, so thinking about rewriting the whole CSS setup. Doesn't matter for now.
> 
> Thanks!

Done with that. Looking for other issues now. Thanks!

2019-11-21 22:39 UTC, flowirtz approved these changes
Thanks!

2019-11-21 22:40 UTC, merged